# Generated by Django 3.2.7 on 2021-09-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ['-date']},
        ),
    ]
